/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pluralflights;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
